// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZT6WBlHWaAJibiosDE8PpRvySOoGogo',
    appId: '1:31172218743:web:2c42975cb5cc62257c5b72',
    messagingSenderId: '31172218743',
    projectId: 'n9driverapp',
    authDomain: 'n9driverapp.firebaseapp.com',
    databaseURL: 'https://n9driverapp-default-rtdb.firebaseio.com',
    storageBucket: 'n9driverapp.appspot.com',
    measurementId: 'G-77EXT722PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpyrJlOBgcTcOgCsZqqLv_gdq_7lUUi34',
    appId: '1:31172218743:android:0451162c780fdecb7c5b72',
    messagingSenderId: '31172218743',
    projectId: 'n9driverapp',
    databaseURL: 'https://n9driverapp-default-rtdb.firebaseio.com',
    storageBucket: 'n9driverapp.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZT6WBlHWaAJibiosDE8PpRvySOoGogo',
    appId: '1:31172218743:web:9e930e16f7e11e0d7c5b72',
    messagingSenderId: '31172218743',
    projectId: 'n9driverapp',
    authDomain: 'n9driverapp.firebaseapp.com',
    databaseURL: 'https://n9driverapp-default-rtdb.firebaseio.com',
    storageBucket: 'n9driverapp.appspot.com',
    measurementId: 'G-HH7CTCLYMB',
  );
}
